azs:
- name: us-east1-d
  cloud_properties:
    zone: us-east1-d
- name: us-east1-c
  cloud_properties:
    zone: us-east1-c

vm_types:
- name: common
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-ssd

compilation:
  workers: 2
  network: public
  reuse_compilation_vms: true
  az: us-east1-d
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
    preemptible: true

networks:
  - name: public
    type: manual
    subnets:
    - az: us-east1-d
      range: 10.244.0.0/28
      gateway: 10.244.0.1
      cloud_properties:
        network_name: bosh
        subnetwork_name: learning-bosh-us-east1
        ephemeral_external_ip: true
        tags:
          - public
