---
name: learn-bosh
director_uuid: dc7ba28e-7d87-4689-bd6f-841ab8a2eee0

releases:
- name: learn-bosh
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3312.9

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

instance-groups:
- name: server
  instances: 1
  azs: [ us-east1-d ]
  jobs:
  - name: app
    release: learn-bosh
  stemcell: default
  networks: public
